### ISSUE TITLE
Crash on Mapzen SDK Demo app trying to Polyline or Route Line demos

### ISSUE THREAD

**Issue by msmollin** [mapzen/android#148]
Device: Nexus 5

OS: Android 4.4.4

``````
 E/AndroidRuntime( 4151): FATAL EXCEPTION: main
E/AndroidRuntime( 4151): Process: com.mapzen.android.sample, PID: 4151
E/AndroidRuntime( 4151): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapzen.android.sample/com.mapzen.android.sample.PolylineMapzenActivity}: android.view.InflateException: Binary XML file line #1: Error inflating class com.mapzen.android.MapView
E/AndroidRuntime( 4151):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime( 4151):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime( 4151):    at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 4151):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 4151):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4151):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4151):    at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 4151):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4151):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4151):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 4151):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 4151):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4151): Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class com.mapzen.android.MapView
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 4151):    at com.mapzen.android.MapFragment.onCreateView(MapFragment.java:20)
E/AndroidRuntime( 4151):    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
E/AndroidRuntime( 4151):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
E/AndroidRuntime( 4151):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
E/AndroidRuntime( 4151):    at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
E/AndroidRuntime( 4151):    at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
E/AndroidRuntime( 4151):    at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
E/AndroidRuntime( 4151):    at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
E/AndroidRuntime( 4151):    at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
E/AndroidRuntime( 4151):    at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime( 4151):    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
E/AndroidRuntime( 4151):    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
E/AndroidRuntime( 4151):    at com.mapzen.android.sample.PolylineMapzenActivity.onCreate(PolylineMapzenActivity.java:24)
E/AndroidRuntime( 4151):    at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 4151):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 4151):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime( 4151):    ... 11 more
E/AndroidRuntime( 4151): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 4151):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 4151):    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime( 4151):    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime( 4151):    ... 34 more
E/AndroidRuntime( 4151): Caused by: java.lang.StackOverflowError
E/AndroidRuntime( 4151):    at java.lang.ref.FinalizerReference.<init>(FinalizerReference.java:42)
E/AndroidRuntime( 4151):    at java.lang.ref.FinalizerReference.add(FinalizerReference.java:54)
E/AndroidRuntime( 4151):    at android.graphics.Paint.<init>(Paint.java:445)
E/AndroidRuntime( 4151):    at android.graphics.drawable.GradientDrawable.<init>(GradientDrawable.java:116)
E/AndroidRuntime( 4151):    at android.graphics.drawable.GradientDrawable.<init>(GradientDrawable.java:155)
E/AndroidRuntime( 4151):    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:908)
E/AndroidRuntime( 4151):    at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:168)
E/AndroidRuntime( 4151):    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
E/AndroidRuntime( 4151):    at android.graphics.drawable.Drawable.c
D/dalvikvm( 4151): GC_CONCURRENT freed 316K, 2% free 17358K/17708K, paused 0ms+2ms, total 12ms```
``````

**Comment by sarahlensing** [comment]
No longer an issue
