### ISSUE TITLE
NoSuchMethodError in Search example

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/android#237]
### Description
The search example is currently broken with this log:

```
01-04 18:18:21.775 13572-13572/com.mapzen.android.sdk.sample E/PeliasSearchView: Unable to fetch autocomplete results
                                                                                 java.lang.NoSuchMethodError: No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes (declaration of 'com.google.gson.Gson' appears in /data/data/com.mapzen.android.sdk.sample/files/instant-run/dex/slice-jarjar-deps_12d46623b8f14e84f1d9c90b9bd26673dd85c0bd-classes.dex)
                                                                                     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:35)
                                                                                     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
                                                                                     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
                                                                                     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                                                                                     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:106)
                                                                                     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
```

**Comment by sarahlensing** [comment]
User error here...I had a bad copy of pelias in my local m2 repo

**Comment by iamya5in** [comment]
@sarahlensing I'm facing a similar problem. what was your solution?


`
E/HomeActivity: onFailure: 
                                                                            java.lang.NoSuchMethodError: No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes (declaration of 'com.google.gson.Gson' appears in /data/app/com.cloudwell.paywell.services-x7_J__T18s9DlfjchJCMXA==/split_lib_dependencies_apk.apk:classes83.dex)
                                                                                at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:35)
                                                                                at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
                                                                                at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
                                                                                at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
                                                                                at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:112)
                                                                                at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                                at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                at java.lang.Thread.run(Thread.java:764)`

**Comment by sarahcodes100** [comment]
I suspect this is due to the way all app dependencies are resolved by the build system. Are you using gradle to build? If so, can you list your app dependencies as well as the app output for ‘./gradlew dependencies’. You’re likely declaring a dependency on a different version of gson which when resolved is not backwards compatible with all code paths
