### ISSUE TITLE
Circle CI docs task failing

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#296]
```
tickle-circle mapzen documentation master $CIRCLE_TOKEN
Found previous build #1280 for https://github.com/mapzen/documentation
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.10/bin/tickle-circle", line 9, in <module>
    load_entry_point('Circle-Tickler==1.0.1', 'console_scripts', 'tickle-circle')()
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/tickle_circle/__init__.py", line 33, in main
    print('Retrying at {build_url}'.format(**posted.json()))
KeyError: 'build_url'

tickle-circle mapzen documentation master $CIRCLE_TOKEN returned exit code 1

Action failed: tickle-circle mapzen documentation master $CIRCLE_TOKEN
```

**Comment by ecgreb** [comment]
Updated circle ci token in secure environment vars
